name: Build tauri-app

on:
  push:
    paths:
      - .github/workflows/tauri-app.yml
      - tauri-app/**

defaults:
  run:
    working-directory: tauri-app

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: npm ci
      - run: npm run tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: tauri-app
          path: tauri-app/src-tauri/target/release/bundle/msi/*
